name: Playwright Tests
on:
    push:
        branches: [main]
    # pull_request:
    #   branches: [ main ]

jobs:
    Run_test:
        runs-on: ubuntu-20.04 # Choosing OS
        strategy:
            matrix:
                node-version: [14.17.0]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
              # trying to install npm packages
            - run: npm i -g npm@latest
            - run: npm i
            - run: npx playwright install --with-deps
            - run: npm install allure-commandline --save-dev
            - name: run test
              # trying to run tests
              run: npx playwright test
            - name: Create Report
              if: always()
              run: npx allure generate ./allure-results --clean
            - name: Upload artifact allure-report
              uses: actions/upload-artifact@v1
              if: always()
              with:
                  name: allure-report
                  path: ./allure-report
            - name: Deploy report to Github Pages
              if: always()
              uses: peaceiris/actions-gh-pages@v2
              env:
                  PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  PUBLISH_BRANCH: gh-pages
                  PUBLISH_DIR: allure-history
